language: ruby
rvm:
- ruby-head
- 2.4.3
- 2.3.6
- 2.2.8
- 2.1.10
- 2.0.0-p648
matrix:
  allow_failures:
  - rvm: ruby-head
deploy:
  provider: rubygems
  api_key:
    secure: PLHZ+N2quWfUJgMR0Ckt/w51KW1GYruC9Ebo6hGs9rx1tLQqMSAkhRIj1YRzU/KacWqUEwCw8onHswBowzf2H3enWlYvyQ8jcLWuZCpATAukOHP5SnmUqV8EqIqD9A0cX1vemU/7Eg2HQ1aq3bnNbqhZWs2JeTw7NsguPjoWikI=
  gem: faraday_middleware-parse_csv
  on:
    repo: benSlaughter/faraday_middleware-parse_csv
    branch: master